name: Build & Release

on:
  workflow_dispatch:
  push:
    branches:
      - feat/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Play Store key
        run: echo "$PLAY_STORE_JSON_KEY" > play-store-key.json
        env:
          PLAY_STORE_JSON_KEY: ${{ secrets.PLAY_STORE_JSON_KEY }}

#      - name: Build AAB
#        run: ./gradlew bundleRelease

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: play-store-key.json
          packageName: com.paulcoding.hviewer
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          releaseFiles: app-release.aab
          track: release
          status: draft